# Site settings
title: MaksPilot
description: Compare Excel and CSV files effortlessly
url: "https://makspilot.com"
baseurl: ""

# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

permalink: pretty

# Clean URLs without .html extension
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: null

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - CNAME
