plugins:
  - jekyll-redirect-from

permalink: pretty

# Remove .html extension and redirect index.html
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: null
      
# Redirect index.html to clean URLs
redirect_from:
  - /index.html
  - /*/index.html
